import type { Metadata } from 'next';
import { site } from './site';
import { defaultLocale, enabledLocales, localeHref, localeMeta, type Locale } from './i18n';

type BuildMetadataInput = {
  title: string;
  description: string;
  /** Route path without locale prefix, e.g. "/projects". */
  path: string;
  locale?: Locale;
  /** Falls back to the generated PNG when the file is not a raster image. */
  image?: SocialImage;
  type?: 'website' | 'article';
  publishedTime?: string;
  modifiedTime?: string;
  noIndex?: boolean;
  keywords?: string[];
  /** Skips the "| NP88 Solar — …" suffix for titles that already carry it. */
  titleAbsolute?: boolean;
};

/**
 * Default social image — the PNG generated by `src/app/opengraph-image.tsx`.
 *
 * It is attached explicitly to every page rather than relying on the file
 * convention to cascade: a page that exports its own `openGraph` object
 * replaces the inherited one, so pages would otherwise ship with no og:image.
 */
export const DEFAULT_OG_PATH = '/opengraph-image';

export type SocialImage = { url: string; width?: number; height?: number; alt?: string };

const DEFAULT_OG: Required<SocialImage> = {
  url: DEFAULT_OG_PATH,
  width: 1200,
  height: 630,
  alt: 'NP88 Solar — ออกแบบและติดตั้งระบบ Solar Rooftop เชียงใหม่',
};

export function absoluteUrl(path: string): string {
  if (/^https?:\/\//i.test(path)) return path;
  return `${site.url}${path.startsWith('/') ? path : `/${path}`}`;
}

/** true for raster formats every social platform and Google can actually render. */
function isRasterImage(url: string): boolean {
  const pathname = url.split('?')[0].split('#')[0].toLowerCase();
  return /\.(jpe?g|png|webp|gif)$/.test(pathname);
}

/**
 * Picks the image a social platform or Google will actually display.
 *
 * Facebook, LINE and X do not render SVG `og:image`, and Google rejects SVG for
 * Article structured data — so a page whose artwork is still a vector
 * placeholder must fall back to the generated PNG rather than ship a preview
 * that renders as nothing.
 *
 * `/opengraph-image` is extension-less (a Next route, not a file), so it is
 * allowed through explicitly. Everything else must be a raster file; the moment
 * NP88 Solar supplies real `.jpg` / `.webp` photography, those pass this check
 * and become the preview automatically, with no code change.
 */
export function resolveSocialImage(image?: SocialImage): Required<SocialImage> {
  if (!image?.url) return DEFAULT_OG;
  if (image.url === DEFAULT_OG_PATH || isRasterImage(image.url)) {
    return {
      url: image.url,
      width: image.width ?? DEFAULT_OG.width,
      height: image.height ?? DEFAULT_OG.height,
      alt: image.alt ?? DEFAULT_OG.alt,
    };
  }
  return DEFAULT_OG;
}

/** Absolute URL of the social image for a page, after the raster fallback. */
export function socialImageUrl(image?: SocialImage): string {
  return absoluteUrl(resolveSocialImage(image).url);
}

export function buildMetadata({
  title,
  description,
  path,
  locale = defaultLocale,
  image,
  type = 'website',
  publishedTime,
  modifiedTime,
  noIndex = false,
  keywords,
  titleAbsolute = false,
}: BuildMetadataInput): Metadata {
  const canonicalPath = localeHref(path, locale);
  const canonical = absoluteUrl(canonicalPath);
  const og = resolveSocialImage(image);

  // hreflang map — populated automatically as locales are enabled.
  const languages: Record<string, string> = {};
  for (const l of enabledLocales) {
    languages[localeMeta[l].htmlLang] = absoluteUrl(localeHref(path, l));
  }
  languages['x-default'] = absoluteUrl(localeHref(path, defaultLocale));

  return {
    title: titleAbsolute ? { absolute: title } : title,
    description,
    keywords,
    alternates: { canonical, languages },
    robots: noIndex
      ? { index: false, follow: false }
      : {
          index: true,
          follow: true,
          googleBot: { index: true, follow: true, 'max-image-preview': 'large' },
        },
    openGraph: {
      type,
      title,
      description,
      url: canonical,
      siteName: site.name,
      locale: localeMeta[locale].ogLocale,
      images: [
        {
          url: absoluteUrl(og.url),
          width: og.width,
          height: og.height,
          alt: og.alt,
        },
      ],
      ...(type === 'article' ? { publishedTime, modifiedTime } : {}),
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [absoluteUrl(og.url)],
    },
  };
}

/**
 * Page titles. The layout template appends the brand only — keeping the whole
 * title inside the ~60–70 character window search results actually display,
 * even for the long project titles.
 */
export const titleTemplate = `%s | ${site.name}`;
